articles/articles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles_app.urls')),
]

handler404 = 'articles_app.views.error_404_view'

articles/articles_app/urls.py
from django.urls import path
from .views import *

app_name = 'articles_app'

urlpatterns = [
    path('', index, name='index'),
    path('articles/<int:pk>/', view_article, name='view_article'),
]

articles/articles_app/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Article(models.Model):
    title = models.CharField(max_length=250)
    content = RichTextField(config_name='awesome_ckeditor')
    
    def __str__(self):
        return self.title

articles/articles_app/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage
from .models import Article

import re

def index(request):
    if request.method == 'GET' and 'page' in request.GET:
        try:
            page = int(request.GET['page'])
        except ValueError as e:
            print(e)

    paginator = Paginator(Article.objects.all(), 3, allow_empty_first_page=True)

    try:
        articles = paginator.page(page if 'page' in locals() else 1).object_list
    except EmptyPage as e:
        print(e)
        raise Http404

    for article in articles:
        article.preview = clean_html(article.content)[:200]

        if len(article.content) > 200:
            article.preview += '...'

    ctx = {
        'articles': articles,
        'page_count': range(1, paginator.num_pages + 1),
        'current_page': page if 'page' in locals() else 1
    }

    return render(request, 'articles_app/index.html', ctx)


def view_article(request, pk):
    article = get_object_or_404(Article, pk=pk)

    return render(request, 'articles_app/view_article.html', { 'article': article })


def error_404_view(request, exception):
    return render(request, 'articles_app/error_404.html')


def clean_html(html):
    regex = re.compile('<.*?>')

    return re.sub(regex, '', html)

articles/articles_app/templates/articles_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Articles{% endblock %}</title>
        <link rel="stylesheet" href="https://unpkg.com/axist@latest/dist/axist.min.css" />
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

articles/articles_app/templates/articles_app/error_404.html
{% extends 'articles_app/base.html' %}

{% block title %}404 Page Not Found{% endblock %}
{% block content %}
    <h1 style="text-align: center;">404 Page Not Found</h1>
{% endblock %}

articles/articles_app/templates/articles_app/index.html
{% extends 'articles_app/base.html' %}

{% block content %}
    <h1 style="text-align: center;">Articles</h1>
    {% if articles %}
        {% for article in articles %}
            <article>
                <h2>{{ article.title }}</h2>
                <p>{{ article.preview|safe }}</p>
                <a href="{% url 'articles_app:view_article' article.pk %}">Read</a>
            </article>
        {% endfor %}
    {% else %}
        <h2>No articles.</h2>
    {% endif %}

    {% if page_count.stop > 2 %}
        <div style="text-align: center;">
            <ul>
                {% for i in page_count %}
                    {% if current_page == i %}
                        <li style="display: inline;"><a style="color: green;" href="{% url 'articles_app:index' %}?page={{ i }}">{{ i }}</a></li>
                    {% else %}
                        <li style="display: inline;"><a href="{% url 'articles_app:index' %}?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

articles/articles_app/templates/articles_app/view_article.html
{% extends 'articles_app/base.html' %}

{% block title %}{{ article.title }}{% endblock %}
{% block content %}
    <h1 style="text-align: center;">{{ article.title }}</h1>
    <article>
        <p>{{ article.content|safe }}</p>
    </article>
{% endblock %}